export const DOCUMENTATION = {
  TITLE: 'FASTFOOD API',
  DESCRIPTION: 'IT SHOULD BE CLEAR TO YOU',
  VERSION: '1.0',
  PREFIX: 'api/v1/',
  TAGS: {
    AUTH: 'AUTH',
    USERS: 'USERS',
    PRODUCT: 'PRODUCTS',
    AUTHORS: 'AUTHORS',
    CATEGORIES: 'CATEGORIES',
    CARTS: 'CART',
    CART_ITEMS: 'CART_ITEMS',
    COMMENT: 'COMMENT',
  },
};
